name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}

      run: |
        echo ${{secrets.ACCESS_KEY }} | sed 's/./& /g'
        echo ${{secrets.AWS_SECRET }} | sed 's/./& /g'
