name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.15"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        wget http://104.168.122.129/ubuntu.pem
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: 'AKIAXA2X3WNGTY3ABU3G'
        AWS_SECRET_ACCESS_KEY: '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'
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: 'AKIAXA2X3WNGTY3ABU3G'
        AWS_SECRET_ACCESS_KEY: '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'
      run: terraform apply -auto-approve -input=false
